### ISSUE TITLE
como lo puedo implementar tanto para entrada como salida 

### ISSUE THREAD

**Issue by JeanCorreaBarros** [argyleink/transition.css#50]

**Comment by argyleink** [comment]
I clicked each in the transition.style site, pasted the results, and changed the CSS selector to `.entrada`:

![Screenshot 2023-09-06 3 23 05 PM](https://github.com/argyleink/transition.css/assets/1134620/ceff83f8-affd-4737-be6a-381a4778878b)


```css
@keyframes circle-in-hesitate {
  0% {
    clip-path: circle(0%);
  }
  40% {
    clip-path: circle(40%);
  }
  100% {
    clip-path: circle(125%);
  }
}

@keyframes circle-out-hesitate {
  0% {
    clip-path: circle(125%);
  }
  40% {
    clip-path: circle(40%);
  }
  100% {
    clip-path: circle(0%);
  }
}

.salida {
  animation: 2.5s cubic-bezier(.25, 1, .30, 1) circle-out-hesitate both;
}

.entrada {
  animation: 2.5s cubic-bezier(.25, 1, .30, 1) circle-in-hesitate both;
}
```

that help you? 🙂
