### ISSUE TITLE
Add cinematic transition

### ISSUE THREAD

**Issue by argyleink** [argyleink/transition.css#9]
Like hesitate, but goes to 16:9 in the middle

**Comment by argyleink** [comment]
```css
@keyframes wipe-cinematic-out {
  0% {
    clip-path: inset(0 0 0 0);
  }
  30%, 70% {
    clip-path: inset(10% 0 10% 0);
  }
  100% {
    clip-path: inset(100% 0 100% 0);
  }
}
```

```css
@keyframes wipe-cinematic-in {
  0% {
    clip-path: inset(100% 0 100% 0);
  }
  30%, 70% {
    clip-path: inset(10% 0 10% 0);
  }
  100% {
    clip-path: inset(0 0 0 0);
  }
}
```

looks like it's just 2 new css custom props and then the work to teach all the parts of this build system to include the files
